#!/bin/bash
set -x
tclsh rms.tcl
if command -v python2 &> /dev/null; then
    python2 rms.py
    python2 rms_array_numpy.py
    python2 rms_for_numba.py
    python2 rms_for_numba_numpy.py
fi
if command -v python &> /dev/null; then
    python rms.py
    python rms_array_numpy.py
    python rms_for_numba.py
    python rms_for_numba_numpy.py
    python rms_array_numpy_jax.py
fi
if command -v python3 &> /dev/null; then
    python3 rms.py
    python3 rms_array_numpy.py
    python3 rms_for_numba.py
    python3 rms_for_numba_numpy.py
    python3 rms_array_numpy_jax.py
fi
if command -v python3.11 &> /dev/null; then
    python3.11 rms.py
    python3.11 rms_array_numpy.py
    python3.11 rms_for_numba.py
    python3.11 rms_for_numba_numpy.py
    python3.11 rms_array_numpy_jax.py
fi
rm -f rms{1,2,3,3fast}
gcc -O1 -Wall -DVERSION=\"`gcc -dumpversion`\" rms.c -lm -o rms1 && ./rms1
gcc -O2 -Wall -DVERSION=\"`gcc -dumpversion`\" rms.c -lm -o rms2 && ./rms2
gcc -O3 -Wall -DVERSION=\"`gcc -dumpversion`\" rms.c -lm -o rms3 && ./rms3
gcc -Ofast -Wall -DVERSION=\"`gcc -dumpversion`\" rms.c -lm -o rms3fast && ./rms3fast
rm -f rms_threaded{1,2,3,3fast}
gcc -O1 -Wall -DVERSION=\"`gcc -dumpversion`\" rms_threaded.c -fopenmp -lm -o rms_threaded1 && ./rms_threaded1
gcc -O2 -Wall -DVERSION=\"`gcc -dumpversion`\" rms_threaded.c -fopenmp -lm -o rms_threaded2 && ./rms_threaded2
gcc -O3 -Wall -DVERSION=\"`gcc -dumpversion`\" rms_threaded.c -fopenmp -lm -o rms_threaded3 && ./rms_threaded3
gcc -Ofast -Wall -DVERSION=\"`gcc -dumpversion`\" rms_threaded.c -fopenmp -lm -o rms_threaded3fast && ./rms_threaded3fast
julia --project rms_array.jl
julia --project rms.jl
julia --project rms_generator.jl
julia --project rms_eachindex.jl
julia --project rms_simd.jl
julia --project rms_fastmath.jl
julia --project rms_turbo.jl
julia --project -t4 rms_tturbo.jl
julia --project -t8 rms_tturbo.jl
julia --project -tauto rms_tturbo.jl
